### PR TITLE
Add docs to when.py

### PR DESCRIPTION
**Pull request by steventrouble**
Document Every, Ratio, and Clock so that it's more immediately clear how to use it

### CODE REVIEW

**Comment by steventrouble** [comment]
?

**Comment by danijar** [comment]
Thanks, but I'm not interested in adding documentation. Most of the time, it takes up more space than is worth it. And to understand what's happening, looking at the code is safer than trusting documentation :)

**Comment by steventrouble** [comment]
I understand the sentiment, but there is a balance to be had. Not all code can be self-documenting, and a class called "Every" isn't exactly self-explanatory.

Here's the relevant section of the [Google Python style guide](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods):


> A docstring is mandatory for every function that has one or more of the following properties:
> *   being part of the public API
> *   nontrivial size
> *   non-obvious logic

(BTW, I helped administrate the readability program at Google so I'm pretty familiar with the best practices on writing readable code.)

**Comment by orybkin** [comment]
> Most of the time, it takes up more space than is worth it

Is there a way to automatically collapse the documentation for people who don't need it?

**Pull request closed without merging**
