### PR TITLE
Hybrid Action Spaces

### PR DESCRIPTION
**Pull request by Pippo809**
I have integrated the usage of hybrid action spaces. Action Spaces can be dicts with keys ("Continous"/"Discrete").
The Actor Critic will have 2 separate heads for each action type, generating a Continous distribution and a discrete one (still using the config options, eg. normal/one-hot etc). The RSSM world model concatenates the actions and trains as before.

### CODE REVIEW

**Comment by Lr-2002** [comment]
Your code seems to change the action to Continous and Discrete, Is it possible for me to change the agent to give out a dict with something like 1.actor 2. action ?Do you have some recommendation ?

**Comment by Lr-2002** [comment]
What's more, Do you have any example to test in your code ?

**Comment by Lr-2002** [comment]
What's more Could the code output Continous with Discrete together ?

**Comment by danijar** [comment]
Dict and hybrid action spaces are now supported natively.

**Pull request closed without merging**
